name: |
  Switch production to non LIVE (when not ready to go LIVE, but want to test on production env)
  See https://docs-ui-kit-btplc.ps.intdigital.ee.co.uk/docs/ci-cd/blue-green

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "This action will disable blue/green and will remove the app from LIVE CDN, you should still be able to access internally using non-live version, Are you sure what are you doing? Select master from above and type below, 'I know what I am doing' to confirm"
        required: true

jobs:
  Deploy:
    if: github.event.inputs.confirm=='I know what I am doing'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version:
          - 12.13

    steps:
      - name: Check branch (Only works on master)
        if: github.ref != 'refs/heads/master'
        run: |
          echo Should be triggered only from master branch
          exit 1
      - uses: actions/checkout@master

      - uses: actions/checkout@v2
        with:
          repository: btplc/github-actions
          path: .github/actions
          token: ${{ secrets.GIT_PAT }}
      - name: Install actions
        run: cd .github/actions && yarn --frozen-lockfile

      - name: Get stack info
        uses: ./.github/actions/dist/actions/getStackInfo
        id: getStackInfo
        with:
          getCurrentHttpStatus: true
          root: ${{github.workspace}}
          ref: ${{ github.ref }}
          repo: ${{ github.repository }}

      - name: Update reverse proxy
        uses: ./.github/actions/dist/actions/jenkins-job
        with:
          url: ${{ secrets.JENKINS_URL }}
          username: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          jobName: github-job-apigw-routes-toggle
          jobParams: |
            platform=${{steps.getStackInfo.outputs.platform}}
            stage=${{steps.getStackInfo.outputs.stage}}
            uri=${{steps.getStackInfo.outputs.basePath}}
            origin=${{steps.getStackInfo.outputs.origin}}
            serverlessVersion=2.1.10
            nonLiveApiId=${{ secrets.EE_API_GW_PRODUCTION_NON_LIVE }}
