name: Show current blue/green status (Only works on master)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "This action will Show current status and where the next stack will be deployed to"
        required: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version:
          - 12.13

    steps:
      - name: Check branch (Only works on master)
        if: github.ref != 'refs/heads/master'
        run: |
          echo Should be triggered only from master branch
          exit 1

      - uses: actions/checkout@master

      - uses: actions/checkout@v2
        with:
          repository: btplc/github-actions
          path: .github/actions
          token: ${{ secrets.GIT_PAT }}
      - name: Install actions
        run: cd .github/actions && yarn --frozen-lockfile

      - name: Get stack info
        uses: ./.github/actions/dist/actions/getStackInfo
        id: getStackInfo
        with:
          getCurrentHttpStatus: true
          root: ${{github.workspace}}
          ref: ${{ github.ref }}
          repo: ${{ github.repository }}

      - name: Find current blue/green status
        uses: ./.github/actions/dist/actions/jenkins-job
        id: blue-green-status
        with:
          url: ${{ secrets.JENKINS_URL }}
          username: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          jobName: github-job-blue-green-status
          jobParams: |
            platform=${{steps.getStackInfo.outputs.platform}}
            stage=${{steps.getStackInfo.outputs.stage}}
            serverlessVersion=2.1.10
