name: Built Lint Test

on: [push]

jobs:
  build-lint-test:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Restore node_modules from cache
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - run: echo "" >> .npmrc
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> .npmrc
    - name: Install dependancies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn lint
    - run: yarn test
