name: Check A11y Checklist

on:
  pull_request:
    branches:
      - develop # Feature envs after creating/Updating PRs
    types: [opened, edited, reopened]

jobs:
  a11y-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [12.13]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: btplc/github-actions
          path: .github/actions
          token: ${{ secrets.GIT_PAT }}

      - name: Install actions
        run: cd .github/actions && yarn --frozen-lockfile

      - name: Check PR A11y Checklist
        uses: ./.github/actions/dist/actions/accessibility/pr-checklist-analyser
        id: check-pr-a11y-checklist
