name: Draft release

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    strategy:
      matrix:
        node-version:
          - 12.10

    steps:
      - uses: actions/checkout@master
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
