name: Deploy to production

on:
  release:
    types:
      - published

jobs:
  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version:
          - 12.13

    steps:
      - uses: actions/checkout@master
      - name: Install
        run: |
          echo "" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> .npmrc
          yarn install --frozen-lockfile --ignore-scripts

      - name: Checkout actions repo
        uses: actions/checkout@v2
        with:
          repository: btplc/github-actions
          path: .github/actions
          token: ${{ secrets.GIT_PAT }}
      - name: Install actions
        run: cd .github/actions && yarn --frozen-lockfile

      - name: Get stack info
        uses: ./.github/actions/dist/actions/getStackInfo
        id: getStackInfo
        with:
          getCurrentHttpStatus: true
          root: ${{github.workspace}}
          ref: master
          repo: ${{ github.repository }}
          # There is no SSL certificate installed for bt on production account,
          dns: ee

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Deploy code
        uses: ./.github/actions/dist/actions/jenkins-job
        with:
          url: ${{ secrets.JENKINS_URL }}
          username: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          jobName: github-job-deploy
          jobParams: |
            platform=${{steps.getStackInfo.outputs.platform}}
            stage=${{steps.getStackInfo.outputs.stage}}
            serverlessVersion=2.1.10
            build.zip=file:${{github.workspace}}/.next
          # Special list of parameters to custom deploy
          # There is no SSL certificate installed for bt,
          # so it should always be --dns=ee for production
          params: |
            --blueGreen
            --webAclName=${{secrets.WEB_ACL_APIGW_ONLY}}
            --accessIdentityId=E1OXS9EK2CUPG4 
            --nodeVersion=nodejs12.x
            --dynatraceMonitored
            --dns=ee
