name: Deploy to production

on:
  release:
    types:
      - published    

jobs:
  Deploy:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: 
        - 12.10

    steps:
      - uses: actions/checkout@master   
      - name: Install
        run: |
          echo "" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> .npmrc
          yarn install --frozen-lockfile --ignore-scripts
      
      - name: Checkout actions repo
        uses: actions/checkout@v2
        with:
          repository: btplc/github-actions
          path: .github/actions
          token: ${{ secrets.GIT_PAT }}
      - name: Install actions
        run: cd .github/actions && yarn --frozen-lockfile    

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Deploy code
        uses: ./.github/actions/jenkins
        id: deployment
        with:
          url: ${{ secrets.JENKINS_URL }}
          username: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          jobName: ${{ secrets.JENKINS_JOB_NAME }}
          ref: master
          repo: ${{ github.repository }}
          params: --accessIdentityId=E1OXS9EK2CUPG4 --nodeVersion=nodejs12.x
          serverlessVersion: 1.14.0
