name: Remove branch/PR stack

on:
  delete:
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'
      - "!master" # excludes master
      - "!develop" # excludes master
  pull_request:
    types:
      - closed
jobs:
  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version:
          - 12.13

    steps:
      - name: Checkout actions repo
        uses: actions/checkout@v2
        with:
          repository: btplc/github-actions
          path: .github/actions
          token: ${{ secrets.GIT_PAT }}
      - name: Install actions
        run: cd .github/actions && yarn --frozen-lockfile

      - name: Remove PR stack
        if: ${{github.event_name=='pull_request'}}
        uses: ./.github/actions/jenkins-remove-stack
        with:
          url: ${{ secrets.JENKINS_URL }}
          username: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          jobName: ${{ secrets.JENKINS_CLEAN_UP_JOB_NAME }}
          ref: refs/pull/${{github.event.pull_request.number}}/merge
          repo: ${{ github.repository }}
          serverlessVersion: 2.1.10
          waitToComplete: false

      - name: Remove branch stack
        if: ${{github.event_name=='delete' && github.event.ref_type== 'branch'}}
        uses: ./.github/actions/jenkins-remove-stack
        with:
          url: ${{ secrets.JENKINS_URL }}
          username: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          jobName: ${{ secrets.JENKINS_CLEAN_UP_JOB_NAME }}
          ref: ${{github.event.ref}}
          repo: ${{ github.repository }}
          serverlessVersion: 2.1.10
          waitToComplete: false
