# GitHub workflow to trigger show logs Jenkins Job
name: Show server logs

on: 
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Or provide PR number'     
        required: false
      gStartTime:
        description: 'Logs needed since (e.g, -1 day, -4 hours, -20 minutes):'     
        required: true
        default: '-1 day'

      gAWS_Regions:
        description: 'AWS regions to be used (provide a , separated list.. e.g. EU, NA):'     
        required: true
        default: 'EU'


jobs:
  show_logs:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: 
        - 12.13

    steps:
      - name: Checkout actions repo
        uses: actions/checkout@v2
        with:
          repository: btplc/github-actions
          path: .github/actions
          token: ${{ secrets.GIT_PAT }}
      - name: Install actions
        run: cd .github/actions && yarn --frozen-lockfile
        
      - name: Set env
        id: setEnv
        if: github.event.inputs.prNumber!=''
        run: echo '::set-output name=PR_REF::refs/pull/${{github.event.inputs.prNumber}}/merge'
   
      - name: Get stack info
        uses: ./.github/actions/dist/actions/getStackInfo
        id: getStackInfo
        with:
          getCurrentHttpStatus: true
          root: ${{github.workspace}}
          ref: ${{ steps.setEnv.outputs.PR_REF || github.ref }}
          repo: ${{ github.repository }}

      - name: Fetch Logs
        uses: ./.github/actions/dist/actions/jenkins-job
        with:
          url: ${{ secrets.JENKINS_URL }}
          username: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          jobName: show_logs2/job/master
          waitToComplete: true
          jobParams: |
            functionName=${{ steps.getStackInfo.outputs.stage }}
            startTime=${{ github.event.inputs.gStartTime }}
            profileName=${{ github.ref=='refs/heads/master' && 'production' || 'non-production' }}
            AWS_Regions=${{ github.event.inputs.gAWS_Regions }}
