name: Unlink Lambdas from terraform state

on:
  workflow_dispatch:
    inputs:
      lambdaFunctionName:
        description: "Lambda Function Name (See https://docs-ui-kit-btplc.ps.intdigital.ee.co.uk/docs/ci-cd/deployment-errors#solution-2)"
        required: true

jobs:
  UpdateTerraformState:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version:
          - 12.13

    steps:
      - name: Checkout actions repo
        uses: actions/checkout@v2
        with:
          repository: btplc/github-actions
          path: .github/actions
          token: ${{ secrets.GIT_PAT }}
      - name: Install actions
        run: cd .github/actions && yarn --frozen-lockfile

      - name: Manage State
        uses: ./.github/actions/jenkins-manage-state
        with:
          url: ${{ secrets.JENKINS_URL }}
          username: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          jobName: github-job-terraform-state
          lambdaFunctionName: ${{ github.event.inputs.lambdaFunctionName }}
          serverlessVersion: 2.1.10
